#!/usr/bin/env bash
# Generates .env.local for local development from the running Supabase stack.
# The Supabase values are the CLI's well-known local demo keys (not secrets).
# Optional third-party integrations are left blank; the app degrades gracefully.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

status=$(supabase status -o json)
get() { echo "$status" | grep -oP "\"$1\": \"\K[^\"]+"; }

cat > .env.local <<EOF
# Auto-generated by scripts/gen-env-local.sh - local development only.
NEXT_PUBLIC_SUPABASE_URL=$(get API_URL)
NEXT_PUBLIC_SUPABASE_ANON_KEY=$(get ANON_KEY)
SUPABASE_SERVICE_ROLE_KEY=$(get SERVICE_ROLE_KEY)

NEXT_PUBLIC_APP_URL=http://localhost:3000

# Optional integrations - unset locally (app degrades gracefully without them).
RESEND_API_KEY=
RESEND_FROM_EMAIL=
XERO_CLIENT_ID=
XERO_CLIENT_SECRET=
XERO_REDIRECT_URI=http://localhost:3000/api/xero/callback
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
STRIPE_PRICE_MONTHLY=
STRIPE_PRICE_ANNUAL=
AI_GATEWAY_API_KEY=
NEXT_PUBLIC_POSTHOG_KEY=
POSTHOG_REGION=us
UPSTASH_REDIS_REST_URL=
UPSTASH_REDIS_REST_TOKEN=
EOF

echo "Wrote .env.local"
